export const SITE_CONFIG = {
  name: 'LUXE IMPORTS',
  tagline: 'GLOBAL LUXURY. DELIVERED.',
  description: 'Bespoke sourcing, import, export and international logistics for premium automobiles, aircraft and marine vessels.',
  url: 'https://luxeimports.com',
  email: 'info@luxeimports.com',
  phone: '+44 20 7123 4567',
  whatsapp: '+447700000000',
};

export const ASSET_TYPES = [
  { value: 'automobile', label: 'Automobile' },
  { value: 'aircraft', label: 'Aircraft' },
  { value: 'yacht', label: 'Yacht' },
  { value: 'boat', label: 'Boat' },
  { value: 'other', label: 'Other' },
] as const;

export const VEHICLE_CATEGORIES = [
  'Supercars',
  'Luxury SUVs',
  'Executive Cars',
  'Classic Cars',
  'Sports Cars',
  'Electric Luxury Cars',
  'Rare & Limited Vehicles',
] as const;

export const AIRCRAFT_CATEGORIES = [
  'Private Jets',
  'Business Jets',
  'Turboprops',
  'Helicopters',
  'Aircraft',
] as const;

export const MARINE_CATEGORIES = [
  'Motor Yachts',
  'Superyachts',
  'Sport Boats',
  'Explorer Yachts',
  'Sailing Yachts',
  'Luxury Boats',
] as const;

export const MANUFACTURERS = [
  'Rolls-Royce',
  'Bentley',
  'Range Rover',
  'Porsche',
  'Mercedes-Benz',
  'Ferrari',
  'Lamborghini',
  'Aston Martin',
  'McLaren',
  'Bugatti',
  'Maserati',
  'BMW',
  'Audi',
  'Land Rover',
  'Tesla',
  'Lucid',
  'Rivian',
] as const;

export const AIRCRAFT_MANUFACTURERS = [
  'Bombardier',
  'Gulfstream',
  'Cessna',
  'Dassault',
  'Embraer',
  'Pilatus',
  'Piper',
  'Airbus',
  'Boeing',
  'Leonardo',
] as const;

export const MARINE_BUILDERS = [
  'Lürssen',
  'Feadship',
  'Benetti',
  'Oceanco',
  'Heesen',
  'Sunseeker',
  'Princess Yachts',
  'Azimut',
  'Ferretti',
  'Sanlorenzo',
  'Westport',
  'Hatteras',
] as const;

export const COUNTRIES = [
  'United Kingdom',
  'Germany',
  'Japan',
  'United Arab Emirates',
  'United States',
  'South Africa',
  'Kenya',
  'France',
  'Italy',
  'Netherlands',
  'Switzerland',
  'Monaco',
  'Singapore',
  'Hong Kong',
  'Australia',
  'Canada',
  'Belgium',
  'Spain',
  'China',
  'South Korea',
] as const;

export const REQUEST_STATUSES = [
  { value: 'REQUESTED', label: 'Request Submitted', step: 0 },
  { value: 'SOURCING', label: 'Global Sourcing', step: 1 },
  { value: 'VERIFICATION', label: 'Asset Verification', step: 2 },
  { value: 'NEGOTIATION', label: 'Price Negotiation', step: 3 },
  { value: 'PURCHASE', label: 'Purchase & Documentation', step: 4 },
  { value: 'SHIPPING', label: 'International Shipping', step: 5 },
  { value: 'CUSTOMS', label: 'Customs Clearance', step: 6 },
  { value: 'DELIVERY', label: 'Final Delivery', step: 7 },
  { value: 'COMPLETED', label: 'Completed', step: 8 },
] as const;

export const SERVICES = [
  {
    title: 'Global Sourcing',
    description: 'We leverage an extensive worldwide network to locate and acquire the finest luxury automobiles, aircraft and marine vessels.',
    icon: 'Globe',
  },
  {
    title: 'Import & Export',
    description: 'Seamless cross-border transactions with full compliance to international trade regulations.',
    icon: 'ArrowLeftRight',
  },
  {
    title: 'Shipping & Logistics',
    description: 'Specialized transport solutions including RoRo, container shipping, air freight and marine transport.',
    icon: 'Truck',
  },
  {
    title: 'Customs Clearance',
    description: 'Expert handling of all customs documentation, duties and regulatory requirements.',
    icon: 'FileCheck',
  },
  {
    title: 'Inspection & Verification',
    description: 'Thorough independent verification of condition, authenticity and specifications.',
    icon: 'Search',
  },
  {
    title: 'Registration Support',
    description: 'Complete assistance with vehicle registration and documentation in your jurisdiction.',
    icon: 'ClipboardCheck',
  },
  {
    title: 'After-Sales Support',
    description: 'Ongoing assistance with maintenance referrals, warranty support and re-export.',
    icon: 'Headphones',
  },
  {
    title: 'Private Client Services',
    description: 'Confidential handling of high-value acquisitions with dedicated personal account management.',
    icon: 'Crown',
  },
] as const;

export const NAVIGATION = [
  { href: '/', label: 'Home' },
  { href: '/automotive', label: 'Automotive' },
  { href: '/aviation', label: 'Aviation' },
  { href: '/marine', label: 'Marine' },
  { href: '/services', label: 'Services' },
  { href: '/about', label: 'About' },
  { href: '/insights', label: 'Insights' },
  { href: '/contact', label: 'Contact' },
] as const;

export const PORTAL_NAVIGATION = [
  { href: '/portal', label: 'Dashboard', icon: 'LayoutDashboard' },
  { href: '/portal/requests', label: 'My Requests', icon: 'FileText' },
  { href: '/portal/quotes', label: 'Quotes', icon: 'Receipt' },
  { href: '/portal/invoices', label: 'Invoices', icon: 'FileSpreadsheet' },
  { href: '/portal/shipments', label: 'Shipments', icon: 'Truck' },
  { href: '/portal/documents', label: 'Documents', icon: 'FolderOpen' },
  { href: '/portal/wishlist', label: 'Wishlist', icon: 'Heart' },
  { href: '/portal/messages', label: 'Messages', icon: 'MessageSquare' },
  { href: '/portal/profile', label: 'Profile', icon: 'User' },
  { href: '/portal/settings', label: 'Settings', icon: 'Settings' },
] as const;

export const ADMIN_NAVIGATION = [
  { href: '/admin', label: 'Dashboard', icon: 'LayoutDashboard' },
  { href: '/admin/requests', label: 'Requests', icon: 'FileText' },
  { href: '/admin/inventory', label: 'Inventory', icon: 'Package' },
  { href: '/admin/clients', label: 'Clients', icon: 'Users' },
  { href: '/admin/shipments', label: 'Shipments', icon: 'Truck' },
  { href: '/admin/quotes', label: 'Quotes', icon: 'Receipt' },
] as const;

export const LOGISTICS_ROUTES = [
  { from: 'United Kingdom', to: 'Germany', label: 'UK ↔ Germany' },
  { from: 'United Kingdom', to: 'Japan', label: 'UK ↔ Japan' },
  { from: 'United Kingdom', to: 'United Arab Emirates', label: 'UK ↔ UAE' },
  { from: 'United Kingdom', to: 'United States', label: 'UK ↔ USA' },
  { from: 'Germany', to: 'Japan', label: 'Germany ↔ Japan' },
  { from: 'Germany', to: 'United Arab Emirates', label: 'Germany ↔ UAE' },
  { from: 'Japan', to: 'United Arab Emirates', label: 'Japan ↔ UAE' },
  { from: 'Japan', to: 'United States', label: 'Japan ↔ USA' },
  { from: 'United States', to: 'South Africa', label: 'USA ↔ South Africa' },
  { from: 'United Arab Emirates', to: 'Kenya', label: 'UAE ↔ Kenya' },
  { from: 'South Africa', to: 'Kenya', label: 'South Africa ↔ Kenya' },
  { from: 'United Kingdom', to: 'South Africa', label: 'UK ↔ South Africa' },
] as const;

export const BLOG_POSTS = [
  {
    slug: 'how-to-import-a-luxury-car',
    title: 'How to Import a Luxury Car',
    excerpt: 'A comprehensive guide to importing high-end vehicles across international borders, covering documentation, customs and logistics.',
    cover_image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80&auto=format',
    category: 'Automotive',
    author: 'Luxe Imports Editorial',
    date: '2026-01-15',
    readTime: '8 min read',
  },
  {
    slug: 'private-jet-buying-guide',
    title: 'Private Jet Buying Guide',
    excerpt: 'Everything you need to know about acquiring a private aircraft — from selection to delivery and registration.',
    cover_image: 'https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=800&q=80&auto=format',
    category: 'Aviation',
    author: 'Luxe Imports Editorial',
    date: '2026-02-10',
    readTime: '10 min read',
  },
  {
    slug: 'yacht-import-shipping-guide',
    title: 'Yacht Import & Shipping Guide',
    excerpt: 'Navigate the complexities of yacht and superyacht international transport with confidence.',
    cover_image: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80&auto=format',
    category: 'Marine',
    author: 'Luxe Imports Editorial',
    date: '2026-03-05',
    readTime: '9 min read',
  },
  {
    slug: 'best-countries-for-luxury-vehicle-sourcing',
    title: 'Best Countries for Luxury Vehicle Sourcing',
    excerpt: 'An analysis of the top markets for sourcing premium automobiles, from Japan\'s pristine used market to Germany\'s direct-from-factory deals.',
    cover_image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80&auto=format',
    category: 'Automotive',
    author: 'Luxe Imports Editorial',
    date: '2026-03-20',
    readTime: '7 min read',
  },
  {
    slug: 'understanding-international-vehicle-shipping',
    title: 'Understanding International Vehicle Shipping',
    excerpt: 'RoRo vs container shipping, insurance considerations, and how to prepare your vehicle for international transport.',
    cover_image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80&auto=format',
    category: 'Logistics',
    author: 'Luxe Imports Editorial',
    date: '2026-04-08',
    readTime: '6 min read',
  },
  {
    slug: 'luxury-asset-investment',
    title: 'Luxury Asset Investment',
    excerpt: 'Why high-net-worth individuals are turning to tangible luxury assets as a portfolio diversification strategy.',
    cover_image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80&auto=format',
    category: 'Insights',
    author: 'Luxe Imports Editorial',
    date: '2026-04-25',
    readTime: '5 min read',
  },
  {
    slug: 'import-documentation-guide',
    title: 'Import Documentation Guide',
    excerpt: 'A detailed walkthrough of every document required for the legal import of luxury vehicles, aircraft and vessels.',
    cover_image: 'https://images.unsplash.com/photo-1569629743817-70d8db6c323b?w=800&q=80&auto=format',
    category: 'Logistics',
    author: 'Luxe Imports Editorial',
    date: '2026-05-12',
    readTime: '8 min read',
  },
] as const;

export const DEMO_VEHICLES = [
  {
    slug: 'rolls-royce-ghost-2024',
    title: 'Rolls-Royce Ghost Extended',
    manufacturer: 'Rolls-Royce',
    model: 'Ghost Extended',
    year: 2024,
    category: 'Executive Cars',
    price: 450000,
    currency: 'USD',
    mileage: 1200,
    color: 'Arctic White',
    engine: '6.75L V12 Twin-Turbo',
    horsepower: 571,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    origin_country: 'United Kingdom',
    location: 'London, UK',
    condition: 'New',
    featured: true,
    published: true,
    description: 'The Rolls-Royce Ghost Extended represents the pinnacle of automotive luxury. With its serene cabin and effortless power, this is travel redefined.',
    estimated_shipping: 8500,
    specifications: {
      'Engine': '6.75L V12 Twin-Turbo',
      'Power': '571 HP',
      'Torque': '850 Nm',
      'Acceleration': '0-60 mph in 4.7s',
      'Top Speed': '155 mph (limited)',
      'Wheelbase': '3,465 mm',
      'Weight': '2,490 kg',
      'Seating': '4-5 passengers',
    },
    images: ['https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=800&q=80&auto=format'],
  },
  {
    slug: 'bentley-continental-gt-2024',
    title: 'Bentley Continental GT Speed',
    manufacturer: 'Bentley',
    model: 'Continental GT Speed',
    year: 2024,
    category: 'Grand Tourer',
    price: 285000,
    currency: 'USD',
    mileage: 3400,
    color: 'Beluga Black',
    engine: '6.0L W12 Twin-Turbo',
    horsepower: 659,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    origin_country: 'United Kingdom',
    location: 'Crewe, UK',
    condition: 'New',
    featured: true,
    published: true,
    description: 'The Continental GT Speed is the fastest and most driver-focused Bentley ever created. A grand tourer without compromise.',
    estimated_shipping: 7200,
    specifications: {
      'Engine': '6.0L W12 Twin-Turbo',
      'Power': '659 HP',
      'Torque': '900 Nm',
      'Acceleration': '0-60 mph in 3.5s',
      'Top Speed': '208 mph',
      'Wheelbase': '2,851 mm',
      'Weight': '2,320 kg',
      'Seating': '4 passengers',
    },
    images: ['https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80&auto=format'],
  },
  {
    slug: 'ferrari-sf90-stradale-2024',
    title: 'Ferrari SF90 Stradale',
    manufacturer: 'Ferrari',
    model: 'SF90 Stradale',
    year: 2024,
    category: 'Supercars',
    price: 625000,
    currency: 'USD',
    mileage: 800,
    color: 'Rosso Corsa',
    engine: '4.0L V8 Twin-Turbo + Electric',
    horsepower: 986,
    transmission: '8-Speed DCT',
    fuel_type: 'Hybrid',
    origin_country: 'Italy',
    location: 'Maranello, Italy',
    condition: 'New',
    featured: true,
    published: true,
    description: 'The SF90 Stradale marks a new era for Ferrari. Hybrid technology meets extreme performance in a car that redefines what a supercar can be.',
    estimated_shipping: 12000,
    specifications: {
      'Engine': '4.0L V8 Twin-Turbo + 3 Electric Motors',
      'Power': '986 HP combined',
      'Torque': '800 Nm (V8) + electric',
      'Acceleration': '0-62 mph in 2.5s',
      'Top Speed': '211 mph',
      'Electric Range': '15.5 miles',
      'Weight': '1,570 kg',
      'Seating': '2 passengers',
    },
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80&auto=format'],
  },
  {
    slug: 'porsche-911-gt3-rs-2024',
    title: 'Porsche 911 GT3 RS',
    manufacturer: 'Porsche',
    model: '911 GT3 RS',
    year: 2024,
    category: 'Sports Cars',
    price: 315000,
    currency: 'USD',
    mileage: 1500,
    color: 'Guards Red',
    engine: '4.0L Flat-6 Naturally Aspirated',
    horsepower: 518,
    transmission: '7-Speed PDK',
    fuel_type: 'Petrol',
    origin_country: 'Germany',
    location: 'Stuttgart, Germany',
    condition: 'New',
    featured: false,
    published: true,
    description: 'The 911 GT3 RS is a road-legal race car. Track-bred performance with Porsche engineering perfection.',
    estimated_shipping: 6800,
    specifications: {
      'Engine': '4.0L Flat-6 NA',
      'Power': '518 HP',
      'Torque': '465 Nm',
      'Acceleration': '0-60 mph in 3.0s',
      'Top Speed': '184 mph',
      'Redline': '9,000 RPM',
      'Weight': '1,450 kg',
      'Seating': '2 passengers',
    },
    images: ['https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&q=80&auto=format'],
  },
  {
    slug: 'mercedes-amg-gt-63-2024',
    title: 'Mercedes-AMG GT 63 S E Performance',
    manufacturer: 'Mercedes-Benz',
    model: 'AMG GT 63 S E Performance',
    year: 2024,
    category: 'Executive Cars',
    price: 245000,
    currency: 'USD',
    mileage: 2100,
    color: 'Obsidian Black',
    engine: '4.0L V8 Biturbo + Electric',
    horsepower: 831,
    transmission: '9-Speed MCT',
    fuel_type: 'Hybrid',
    origin_country: 'Germany',
    location: 'Affalterbach, Germany',
    condition: 'New',
    featured: false,
    published: true,
    description: 'The most powerful Mercedes-AMG ever. A four-door supercar that defies every expectation.',
    estimated_shipping: 7000,
    specifications: {
      'Engine': '4.0L V8 Biturbo + Electric Motor',
      'Power': '831 HP',
      'Torque': '1,470 Nm',
      'Acceleration': '0-62 mph in 2.9s',
      'Top Speed': '196 mph',
      'Electric Range': '7.5 miles',
      'Weight': '2,350 kg',
      'Seating': '4 passengers',
    },
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80&auto=format'],
  },
  {
    slug: 'lamborghini-revuelto-2024',
    title: 'Lamborghini Revuelto',
    manufacturer: 'Lamborghini',
    model: 'Revuelto',
    year: 2024,
    category: 'Supercars',
    price: 680000,
    currency: 'USD',
    mileage: 500,
    color: 'Verde Mantis',
    engine: '6.5L V12 + Electric',
    horsepower: 1001,
    transmission: '8-Speed DCT',
    fuel_type: 'Hybrid',
    origin_country: 'Italy',
    location: 'Sant\'Agata Bolognese, Italy',
    condition: 'New',
    featured: true,
    published: true,
    description: 'The Revuelto is Lamborghini\'s first V12 hybrid. 1,001 horsepower of unbridled Italian passion meets the future.',
    estimated_shipping: 14000,
    specifications: {
      'Engine': '6.5L V12 + 3 Electric Motors',
      'Power': '1,001 HP combined',
      'Torque': '725 Nm (V12)',
      'Acceleration': '0-62 mph in 2.5s',
      'Top Speed': '217+ mph',
      'Electric Range': '6.2 miles',
      'Weight': '1,550 kg dry',
      'Seating': '2 passengers',
    },
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80&auto=format'],
  },
];

export const DEMO_AIRCRAFT = [
  {
    slug: 'bombardier-global-7500-2024',
    title: 'Bombardier Global 7500',
    manufacturer: 'Bombardier',
    model: 'Global 7500',
    year: 2024,
    category: 'Private Jets',
    price: 75000000,
    currency: 'USD',
    range_nm: 7700,
    passengers: 19,
    crew: 4,
    engine_type: 'GE Passport',
    engine_count: 2,
    origin_country: 'Canada',
    location: 'Montreal, Canada',
    condition: 'New',
    featured: true,
    published: true,
    description: 'The Global 7500 is the flagship of business aviation. Unmatched range, comfort and performance for the most discerning travellers.',
    specifications: {
      'Range': '7,700 nm',
      'Speed': 'Mach 0.925',
      'Cabin Length': '16.17 m',
      'Cabin Height': '1.91 m',
      'Baggage': '195 cu ft',
      'Ceiling': '51,000 ft',
      'Takeoff Distance': '5,800 ft',
      'Engines': '2x GE Passport',
    },
    images: ['https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=800&q=80&auto=format'],
  },
  {
    slug: 'gulfstream-g700-2024',
    title: 'Gulfstream G700',
    manufacturer: 'Gulfstream',
    model: 'G700',
    year: 2024,
    category: 'Private Jets',
    price: 65000000,
    currency: 'USD',
    range_nm: 7500,
    passengers: 19,
    crew: 4,
    engine_type: 'Rolls-Royce Pearl 700',
    engine_count: 2,
    origin_country: 'United States',
    location: 'Savannah, USA',
    condition: 'New',
    featured: true,
    published: true,
    description: 'The Gulfstream G700 redefines cabin comfort with the largest, most advanced cabin in business aviation.',
    specifications: {
      'Range': '7,500 nm',
      'Speed': 'Mach 0.925',
      'Cabin Length': '16.01 m',
      'Cabin Height': '1.98 m',
      'Baggage': '195 cu ft',
      'Ceiling': '51,000 ft',
      'Takeoff Distance': '5,600 ft',
      'Engines': '2x Rolls-Royce Pearl 700',
    },
    images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80&auto=format'],
  },
  {
    slug: 'cessna-citation-longitude-2023',
    title: 'Cessna Citation Longitude',
    manufacturer: 'Cessna',
    model: 'Citation Longitude',
    year: 2023,
    category: 'Business Jets',
    price: 28000000,
    currency: 'USD',
    range_nm: 3500,
    passengers: 12,
    crew: 2,
    engine_type: 'Williams FJ44',
    engine_count: 2,
    origin_country: 'United States',
    location: 'Wichita, USA',
    condition: 'Pre-Owned',
    featured: false,
    published: true,
    description: 'The Citation Longitude combines transcontinental range with a superlative cabin experience.',
    specifications: {
      'Range': '3,500 nm',
      'Speed': 'Mach 0.83',
      'Cabin Length': '9.45 m',
      'Cabin Height': '1.83 m',
      'Baggage': '100 cu ft',
      'Ceiling': '45,000 ft',
      'Engines': '2x Williams FJ44-4M',
    },
    images: ['https://images.unsplash.com/photo-1569629743817-70d8db6c323b?w=800&q=80&auto=format'],
  },
  {
    slug: 'pilatus-pc-24-2024',
    title: 'Pilatus PC-24',
    manufacturer: 'Pilatus',
    model: 'PC-24',
    year: 2024,
    category: 'Business Jets',
    price: 12500000,
    currency: 'USD',
    range_nm: 2000,
    passengers: 10,
    crew: 2,
    engine_type: 'Williams FJ44-4A',
    engine_count: 2,
    origin_country: 'Switzerland',
    location: 'Stans, Switzerland',
    condition: 'New',
    featured: false,
    published: true,
    description: 'The PC-24 is the world\'s first Super Versatile Jet. Operates from short and unpaved runways — true freedom of access.',
    specifications: {
      'Range': '2,000 nm',
      'Speed': 'Mach 0.78',
      'Cabin Length': '7.01 m',
      'Cabin Height': '1.74 m',
      'Baggage': '150 cu ft',
      'Ceiling': '45,000 ft',
      'Engines': '2x Williams FJ44-4A',
      'Runway': '2,930 ft (short field)',
    },
    images: ['https://images.unsplash.com/photo-1616432043562-3671ea2e5242?w=800&q=80&auto=format'],
  },
];

export const DEMO_MARINE = [
  {
    slug: 'lurssen-alegria-2023',
    title: 'Lürssen Alegría',
    builder: 'Lürssen',
    model: 'Alegría',
    year: 2023,
    category: 'Superyachts',
    price: 75000000,
    currency: 'USD',
    length_ft: 262,
    cabins: 8,
    capacity: 16,
    engine_type: 'MTU',
    engine_count: 2,
    top_speed_knots: 18,
    range_nm: 5000,
    origin_country: 'Germany',
    location: 'Hamburg, Germany',
    condition: 'New',
    hull_material: 'Steel/Aluminium',
    featured: true,
    published: true,
    description: 'A 80-metre Lürssen masterpiece. Alegria represents the pinnacle of German yacht engineering and timeless design.',
    specifications: {
      'Length': '80m / 262ft',
      'Beam': '12.6m',
      'Draft': '3.2m',
      'Gross Tonnage': '2,010 GT',
      'Cruising Speed': '15 knots',
      'Top Speed': '18 knots',
      'Range': '5,000 nm',
      'Guests': '16 in 8 staterooms',
      'Crew': '20',
      'Builder': 'Lürssen, Germany',
    },
    images: ['https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80&auto=format'],
  },
  {
    slug: 'sunseeker-manhattan-90-2024',
    title: 'Sunseeker Manhattan 90',
    builder: 'Sunseeker',
    model: 'Manhattan 90',
    year: 2024,
    category: 'Motor Yachts',
    price: 8500000,
    currency: 'USD',
    length_ft: 90,
    cabins: 5,
    capacity: 10,
    engine_type: 'MAN V12',
    engine_count: 2,
    top_speed_knots: 30,
    range_nm: 1500,
    origin_country: 'United Kingdom',
    location: 'Poole, UK',
    condition: 'New',
    hull_material: 'Fibreglass',
    featured: true,
    published: true,
    description: 'The Manhattan 90 is Sunseeker\'s finest expression of luxury motor yacht design. Bold, elegant and unmistakably British.',
    specifications: {
      'Length': '27.3m / 90ft',
      'Beam': '6.5m',
      'Draft': '2.0m',
      'Cruising Speed': '24 knots',
      'Top Speed': '30 knots',
      'Range': '1,500 nm',
      'Guests': '10 in 5 cabins',
      'Crew': '4',
      'Builder': 'Sunseeker, UK',
    },
    images: ['https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?w=800&q=80&auto=format'],
  },
  {
    slug: 'azimut-grande-trideck-2024',
    title: 'Azimut Grande Trideck',
    builder: 'Azimut',
    model: 'Grande Trideck',
    year: 2024,
    category: 'Motor Yachts',
    price: 12000000,
    currency: 'USD',
    length_ft: 118,
    cabins: 6,
    capacity: 12,
    engine_type: 'MTU 16V',
    engine_count: 2,
    top_speed_knots: 24,
    range_nm: 3000,
    origin_country: 'Italy',
    location: 'Viareggio, Italy',
    condition: 'New',
    hull_material: 'GRP',
    featured: false,
    published: true,
    description: 'Three decks of Italian elegance. The Grande Trideck is Azimut\'s largest and most ambitious yacht.',
    specifications: {
      'Length': '36m / 118ft',
      'Beam': '8.1m',
      'Draft': '2.3m',
      'Cruising Speed': '20 knots',
      'Top Speed': '24 knots',
      'Range': '3,000 nm',
      'Guests': '12 in 6 cabins',
      'Crew': '7',
      'Builder': 'Azimut, Italy',
    },
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80&auto=format'],
  },
  {
    slug: 'princess-y85-2024',
    title: 'Princess Y85',
    builder: 'Princess Yachts',
    model: 'Y85',
    year: 2024,
    category: 'Motor Yachts',
    price: 6500000,
    currency: 'USD',
    length_ft: 85,
    cabins: 4,
    capacity: 8,
    engine_type: 'MAN V12',
    engine_count: 2,
    top_speed_knots: 28,
    range_nm: 1200,
    origin_country: 'United Kingdom',
    location: 'Plymouth, UK',
    condition: 'New',
    hull_material: 'Fibreglass',
    featured: false,
    published: true,
    description: 'The Y85 combines British craftsmanship with cutting-edge design. A masterpiece of form and function.',
    specifications: {
      'Length': '26.16m / 85ft',
      'Beam': '6.25m',
      'Draft': '1.95m',
      'Cruising Speed': '22 knots',
      'Top Speed': '28 knots',
      'Range': '1,200 nm',
      'Guests': '8 in 4 cabins',
      'Crew': '3',
      'Builder': 'Princess Yachts, UK',
    },
    images: ['https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=80&auto=format'],
  },
];
